### ISSUE TITLE
some package outdated

### ISSUE THREAD

**Issue by khs1994** [aliyun/packagist-mirror#16]
* https://mirrors.aliyun.com/composer/p2/nunomaduro/collision.json
* https://repo.packagist.org/p2/nunomaduro/collision.json

mirror latest version is 5.0.1,but packagist is 5.0.2

**Comment by Seldaek** [comment]
This also caused https://github.com/composer/composer/issues/9343 

I suspect what is happening is sometimes you sync too fast and hit one of our mirror which did not sync yet, so you get still the previous/old file. We handle this case in our mirror script here: https://github.com/composer/mirror/blob/master/mirror.php#L210-L223

Basically the "time" key from the changes.json feed (https://github.com/composer/mirror/blob/master/mirror.php#L125), can be used to know what is the minimum time expected for the file, if you get something older than that you should retry after a few seconds.

**Comment by songshenzong** [comment]
> 这也导致[作曲家/作曲家＃9343](https://github.com/composer/composer/issues/9343)
> 
> 我怀疑发生的情况是有时您同步太快，并且碰到了我们尚未同步的镜像之一，因此您仍然得到先前的/旧的文件。我们在这里的镜像脚本中处理这种情况：[https](https://github.com/composer/mirror/blob/master/mirror.php#L210-L223) : [//github.com/composer/mirror/blob/master/mirror.php#L210-L223](https://github.com/composer/mirror/blob/master/mirror.php#L210-L223)
> 
> 基本上，changes.json供稿（https://github.com/composer/mirror/blob/master/mirror.php#L125）中的“时间”键可用于了解文件的最短时间是多少，如果您发现的东西比该年龄大，则应在几秒钟后重试。

Thank you very much, we will modify our synchronization system.

**Comment by ghost** [comment]
> This also caused [composer/composer#9343](https://github.com/composer/composer/issues/9343)
> 
> I suspect what is happening is sometimes you sync too fast and hit one of our mirror which did not sync yet, so you get still the previous/old file. We handle this case in our mirror script here: https://github.com/composer/mirror/blob/master/mirror.php#L210-L223
> 
> Basically the "time" key from the changes.json feed (https://github.com/composer/mirror/blob/master/mirror.php#L125), can be used to know what is the minimum time expected for the file, if you get something older than that you should retry after a few seconds.

Thank you very much, we will modify our synchronization system.
