### ISSUE TITLE
最近镜像一直不能用，在升级吗？多久能升级完

### ISSUE THREAD

**Issue by lcp0578** [aliyun/packagist-mirror#17]
最近镜像一直不能用，在升级吗？多久能升级完

**Comment by ghost** [comment]
> 最近镜像一直不能用，在升级吗？多久能升级完

请问具体是什么问题？

**Comment by lcp0578** [comment]
@songshenzong 您好，执行composer install或者update的时候有时候会比较卡，大约在十分钟左右都不动，执行过环境是aliyun ECS和自己的macbook，我以为出问题了，https://mirrors.aliyun.com/composer/，访问时被重定向到https://developer.aliyun.com/，composer的官网没有了
